services:
  - type: web
    name: sleep-tracker-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: SUPABASE_URL
        value: https://ivtotnpiopdmqjroqsui.supabase.co
      - key: SUPABASE_KEY
        value: sb_secret_6maP9Cww84Ed8uoj5hlBsw_P6L2SY9p
